# 通知するメッセージの設定
# 使用できるプレースホルダー:
#  {player_name}: 破壊したプレイヤーの表示名
#  {real_player_name}: 破壊したプレイヤーのMCID
#  {count}: 発掘した鉱石の個数
#  {ore}: 鉱石の名前
#  {world}: 発掘したワールド名

message: "&7* &l{player_name}&r &7が &b{count}個&r &7の &b{ore}&7 を発見した!"

# 鉱石の名前を設定
Ores:
  COAL_ORE: "Coal"
  IRON_ORE: "Iron Ore"
  GOLD_ORE: "Gold Ore"
  REDSTONE_ORE: "Redstone Ore"
  LAPIS_ORE: "Lapis"
  EMERALD_ORE: "Emerald"
  DIAMOND_ORE: "Diamond"
  NETHER_QUARTZ_ORE: "Quartz"

# 鉱石を破壊した際、全体通知しないようにするワールドを指定

disableWorlds: []

# 全体通知を無効化する鉱石 ex) COAL_ORE

disableOres: []

# 発掘した鉱石をカウントする最大値

max-vein-size: 100

# クリエイティブモードのプレイヤーが置いた鉱石を、サバイバルモードで破壊した時に全体通知するか

broadcast-creative-placed-blocks: true
