name: OreBroadcast
main: be.bendem.bukkit.orebroadcast.OreBroadcast
version: ${pom.version}
authors: [bendem, Siroshun09]
api-version: "1.16"
description: Send messages to other players when you find ores.
